# Generated by Django 5.2.1 on 2025-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(related_name='courses', to='api.group', verbose_name='Группы'),
        ),
    ]
