# Generated by Django 5.0.2 on 2025-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_course_group_remove_course_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал')], default='absent', max_length=10, verbose_name='Статус посещения'),
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(default='10:30', verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Занятие', max_length=200, verbose_name='Тема занятия'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='-', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('spring', 'Весна'), ('autumn', 'Осень')], default='spring', max_length=6, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
    ]
