# Generated by Django 5.0.2 on 2025-05-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_title_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-year', 'semester', 'name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
